import React ,{useState,useEffect}from 'react';
import {Loader,Card,FormField} from '../Components';
import CreatePost from './CreatePost';

const Home = () => {

    const [loading,setLoadding] = useState(false);
    const [allPosts,setAllPosts] = useState(null);
    const [searchText,setSearchText] = useState("");

    const [searchTimeout, setSearchTimeout] = useState(null);
    const [searchedResults, setSearchedResults] = useState(null);

    
    const fetchPosts = async()=>{
        setLoadding(true);
        try {
            const response= await fetch('http://localhost:8080/api/v1/post',{
                method:'GET',
                headers:{'Content-Type':'application/json'},

            })
            if(response.ok){
                const result = await response.json();
                setAllPosts(result.data.resverse());
            }
        } catch (error) {
            alert(error);
        }finally{
 setLoadding(false);
        }
     }
    useEffect(()=>{
        fetchPosts();
    },[]);

    const handleSearchChange = (e) => {
        clearTimeout(searchTimeout);
        setSearchText(e.target.value);
    
        setSearchTimeout(
          setTimeout(() => {
            const searchResult = allPosts.filter((item) => item.name.toLowerCase().includes(searchText.toLowerCase()) || item.prompt.toLowerCase().includes(searchText.toLowerCase()));
            setSearchedResults(searchResult);
          }, 500),
        );
      };

    const RenderCards = ({data,title}) =>{
        if(data?.length>0) {
            return data.map((post)=><Card key={post._id} {...post}/>)
        }
        return (
            <h2 className='mt-5 font-bold text-[#6449ff] uppercase'>
                {title}
            </h2>
        )
    }

  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>
                The Community Showcase
            </h1> 
            <p className='pt-2 text-[#666e75] text-[14px] max-w-[500px]'>
                Browse through a collection of imaginative and visually stunning images generated by DALL- E AI
            </p>
        </div>
        <div className='mt-16'>
            <FormField/>
        </div>
        <div className='mt-10'>
            {
                loading ? (<div>
                    <Loader/>
                </div>)
                :(
                   <>
                    {
                        searchText && (
                            <h2 className='font-medium text-[#666e75]'>
                                Showing result for <span className='text-[#333328]'>{searchText}</span>
                            </h2>
                        )
                    }
                       <div className="grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3">
              {searchText ? (
                <RenderCards
                  data={searchedResults}
                  title="No Search Results Found"
                />
              ) : (
                <RenderCards
                  data={allPosts}
                  title="No Posts Yet"
                />
              )}
            </div>
                   </> 
                )

            }
        </div>
        <CreatePost/>
    </section>
  )
}

export default Home;